<html>
    <head>
        <title>Ecal test site</title>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
        <script src="<?php echo $this->baseUrl();?>/js/jquery.ui.timepicker.js"></script>
        <script>
            $(function() {
                $( "#startDate" ).datepicker({ dateFormat: "dd/mm/yy" });
                $( "#endDate" ).datepicker({ dateFormat: "dd/mm/yy" });
                $("#startTime").timepicker();
                $("#endTime").timepicker();
            });


        </script>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>